<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="scroll-smooth">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <script>
        // Vanilla JS Dark Mode to prevent FOUC and avoid Alpine <html> binding bugs
        if (localStorage.getItem('darkMode') === 'true' || (!('darkMode' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    </script>

    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- SEO: generated by artesaos/seotools in each controller --}}
    {!! SEO::generate(true) !!}
    @if(isset($noindex_page) && $noindex_page)
    <meta name="robots" content="noindex, follow">
    @else
    <meta name="robots" content="index, follow">
    @endif

    @php
        $currentRouteName = Route::currentRouteName();
        $currentRoute = Route::current();
        $currentRouteParams = $currentRoute ? $currentRoute->parameters() : [];
        
        $baseRouteName = preg_replace('/^bn\./', '', (string)$currentRouteName);
        
        try {
            $queryParams = request()->query();
            $enUrl = $baseRouteName && Route::has($baseRouteName) ? route($baseRouteName, array_merge($currentRouteParams, $queryParams)) : url('/');
            $bnRouteName = 'bn.' . $baseRouteName;
            $bnUrl = $baseRouteName && Route::has($bnRouteName) ? route($bnRouteName, array_merge($currentRouteParams, $queryParams)) : url('/bn');
        } catch (\Exception $e) {
            $enUrl = url('/');
            $bnUrl = url('/bn');
        }
    @endphp
    @if($currentRouteName)
    <link rel="alternate" hreflang="en" href="{{ $enUrl }}" />
    @if(!isset($has_bn_translation) || $has_bn_translation !== false)
    <link rel="alternate" hreflang="bn-BD" href="{{ $bnUrl }}" />
    @endif
    @endif
    <meta name="theme-color" content="#0A2540">
    <meta property="og:site_name" content="{{ setting('site_name', 'DoctorBD24') }}">
    <meta property="og:locale" content="{{ str_replace('-', '_', app()->getLocale() === 'bn' ? 'bn_BD' : 'en_US') }}">
    <meta name="twitter:card" content="summary_large_image">
    @yield('schema')

    {{-- Google Analytics & Search Console --}}
    @if(setting('google_search_console'))
        {!! setting('google_search_console') !!}
    @endif
    @if(setting('google_analytics'))
        {!! setting('google_analytics') !!}
    @endif

    {{-- Favicon --}}
    @php
        $faviconUrl = setting('favicon') ? asset('storage/'.setting('favicon')) : asset('favicon.ico');
    @endphp
    <link rel="icon" type="image/png" sizes="32x32" href="{{ $faviconUrl }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ $faviconUrl }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ $faviconUrl }}">
    <link rel="shortcut icon" href="{{ $faviconUrl }}">
    <link rel="manifest" href="/manifest.json">

    {{-- Fonts --}}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Noto+Sans+Bengali:wght@400;500;600;700&display=optional" rel="stylesheet">

    {{-- Vite assets --}}
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @livewireStyles

    <style>
        :root {
            --clr-primary: #0ea5e9;
            --clr-secondary: #6366f1;
        }
        body { font-family: 'Inter', 'Noto Sans Bengali', sans-serif; }
    </style>
</head>
<body class="bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100 transition-colors duration-300">

    {{-- ═══════════════════════════════════════
         NAVBAR
    ═══════════════════════════════════════ --}}
    <nav class="sticky top-0 z-50 bg-[#0A2540] backdrop-blur-md shadow-sm border-b border-[#0A2540]"
         x-data="{ mobileOpen: false }">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">

                {{-- Logo --}}
                <a href="{{ route('home') }}" class="flex items-center gap-2">
                    @if(setting('site_logo'))
                        <img src="{{ asset('storage/' . setting('site_logo')) }}" alt="{{ setting('site_name', 'DoctorBD24') }}" class="h-9 w-auto bg-white p-1 rounded">
                    @else
                        <div class="w-9 h-9 rounded-xl bg-gradient-to-br from-sky-500 to-indigo-600 flex items-center justify-center shadow-lg">
                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
                            </svg>
                        </div>
                    @endif
                    <span class="text-xl font-extrabold text-white tracking-tight">{{ setting('site_name', 'DoctorBD24') }}</span>
                </a>

                {{-- Desktop nav --}}
                <div class="hidden md:flex items-center gap-6">
                    <a href="{{ route('doctors.index') }}" class="text-sm transition-colors {{ request()->routeIs('doctors.*') ? 'font-extrabold text-sky-400' : 'font-medium text-gray-200 hover:text-sky-400' }}">
                        {{ __('Doctors') }}
                    </a>
                    <a href="{{ route('hospitals.index') }}" class="text-sm transition-colors {{ request()->routeIs('hospitals.*') ? 'font-extrabold text-sky-400' : 'font-medium text-gray-200 hover:text-sky-400' }}">
                        {{ __('Hospitals') }}
                    </a>
                    <a href="{{ route('ambulances.index') }}" class="text-sm transition-colors {{ request()->routeIs('ambulances.*') ? 'font-extrabold text-sky-400' : 'font-medium text-gray-200 hover:text-sky-400' }}">
                        {{ __('Ambulance') }}
                    </a>
                    <a href="{{ route('blog.index') }}" class="text-sm transition-colors {{ request()->routeIs('blog.*') ? 'font-extrabold text-sky-400' : 'font-medium text-gray-200 hover:text-sky-400' }}">
                        {{ __('Blog') }}
                    </a>
                    <a href="{{ route('join.doctor') }}" class="text-sm font-medium px-4 py-2 rounded-lg bg-sky-500 text-white hover:bg-sky-600 transition-colors border border-sky-400">
                        {{ __('Join as Doctor') }}
                    </a>
                </div>

                {{-- Right actions --}}
                <div class="flex items-center gap-3">

                    {{-- Language switcher --}}
                    @if(app()->getLocale() === 'en')
                        @if(isset($has_bn_translation) && $has_bn_translation === false)
                            <button onclick="window.dispatchEvent(new CustomEvent('toast', { detail: { message: 'এই পেইজের বাংলা তথ্য এখনো যুক্ত করা হয়নি', type: 'warning' } }))" class="text-xs font-semibold px-2.5 py-1.5 rounded-lg border border-gray-500 hover:border-sky-400 transition-colors text-gray-200">বাংলা</button>
                        @else
                            <a href="{{ $bnUrl ?? url('/bn') }}" class="text-xs font-semibold px-2.5 py-1.5 rounded-lg border border-gray-500 hover:border-sky-400 transition-colors text-gray-200">বাংলা</a>
                        @endif
                    @else
                        <a href="{{ $enUrl ?? url('/') }}" class="text-xs font-semibold px-2.5 py-1.5 rounded-lg border border-gray-500 hover:border-sky-400 transition-colors text-gray-200">EN</a>
                    @endif

                    {{-- Dark mode --}}
                    <button aria-label="Toggle Dark Mode" onclick="document.documentElement.classList.toggle('dark'); localStorage.setItem('darkMode', document.documentElement.classList.contains('dark'))"
                            class="w-9 h-9 flex items-center justify-center rounded-lg border border-gray-500 hover:border-sky-400 transition-colors text-gray-200">
                        <svg class="dark:hidden w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"/>
                        </svg>
                        <svg class="hidden dark:block w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"/>
                        </svg>
                    </button>

                    {{-- Auth --}}
                    @auth
                        <div class="hidden md:block relative" x-data="{ open: false }">
                            <button aria-label="User Menu" @click="open = !open" @click.away="open = false"
                                class="flex items-center gap-2 px-3 py-1.5 rounded-xl border border-gray-200 dark:border-gray-600 hover:border-sky-400 transition-colors">
                                <div class="w-7 h-7 rounded-lg bg-gradient-to-br from-sky-500 to-indigo-600 flex items-center justify-center text-white text-xs font-black">
                                    {{ mb_substr(auth()->user()->name, 0, 1) }}
                                </div>
                                <span class="text-sm font-medium text-gray-700 dark:text-gray-200 max-w-[80px] truncate">{{ auth()->user()->name }}</span>
                                <svg class="w-3 h-3 text-gray-400 transition-transform" :class="open ? 'rotate-180' : ''" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                            </button>

                            <div x-cloak style="display: none;" x-show="open" x-transition:enter="transition ease-out duration-100"
                                x-transition:enter-start="opacity-0 scale-95" x-transition:enter-end="opacity-100 scale-100"
                                class="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-100 dark:border-gray-700 py-1.5 z-50">
                                @if(!auth()->user()->hasAnyRole(['admin', 'doctor', 'hospital', 'editor', 'moderator']))
                                <a href="{{ route('user.dashboard') }}" class="flex items-center gap-2.5 px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-sky-50 dark:hover:bg-sky-900/30 hover:text-sky-600 transition-colors">
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/></svg>
                                    {{ __('My Dashboard') }}
                                </a>
                                @endif
                                <a href="{{ route('favorites.index') }}" class="flex items-center gap-2.5 px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-red-50 dark:hover:bg-red-900/30 hover:text-red-500 transition-colors">
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/></svg>
                                    {{ __('Favorites') }}
                                </a>
                                @if(auth()->user()->hasRole('admin'))
                                <a href="{{ route('admin.dashboard') }}" class="flex items-center gap-2.5 px-4 py-2 text-sm text-indigo-600 dark:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/30 transition-colors">
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/></svg>
                                    {{ __('Admin Panel') }}
                                </a>
                                @elseif(auth()->user()->hasRole('doctor'))
                                <a href="{{ route('doctor.dashboard') }}" class="flex items-center gap-2.5 px-4 py-2 text-sm text-sky-600 dark:text-sky-400 hover:bg-sky-50 dark:hover:bg-sky-900/30 transition-colors">
                                    <span class="text-sm">👨‍⚕️</span>
                                    {{ __('Doctor Dashboard') }}
                                </a>
                                @elseif(auth()->user()->hasRole('hospital'))
                                <a href="{{ route('hospital.dashboard') }}" class="flex items-center gap-2.5 px-4 py-2 text-sm text-emerald-600 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-900/30 transition-colors">
                                    <span class="text-sm">🏥</span>
                                    {{ __('Hospital Dashboard') }}
                                </a>
                                @endif
                                <div class="border-t border-gray-100 dark:border-gray-700 my-1"></div>
                                <form method="POST" action="{{ route('logout') }}">
                                    @csrf
                                    <button type="submit" class="flex items-center gap-2.5 w-full px-4 py-2 text-sm text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors">
                                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/></svg>
                                        {{ __('Logout') }}
                                    </button>
                                </form>
                            </div>
                        </div>
                    @else
                        <a href="{{ route('login') }}" class="hidden md:block text-sm font-medium px-4 py-2 rounded-lg bg-gradient-to-r from-sky-500 to-indigo-600 text-white hover:opacity-90 shadow transition-all">
                            {{ __('Login') }}
                        </a>
                    @endauth


                    {{-- Mobile hamburger --}}
                    <button aria-label="Toggle Mobile Menu" @click="mobileOpen = !mobileOpen" class="md:hidden w-9 h-9 flex items-center justify-center rounded-lg border border-gray-300 dark:border-gray-600">
                        <svg class="w-5 h-5 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                        </svg>
                    </button>
                </div>
            </div>

            {{-- Mobile menu --}}
            <div x-cloak style="display: none;" x-show="mobileOpen" x-transition class="md:hidden pb-4 pt-2 space-y-1 border-t border-gray-200 dark:border-gray-700 mt-2">
                <a href="{{ route('doctors.index') }}" class="block px-3 py-2 rounded-lg text-sm {{ request()->routeIs('doctors.*') ? 'bg-sky-50 dark:bg-sky-900/40 text-sky-700 dark:text-sky-300 font-bold' : 'text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-gray-800' }}">
                    {{ __('Doctors') }}
                </a>
                <a href="{{ route('hospitals.index') }}" class="block px-3 py-2 rounded-lg text-sm {{ request()->routeIs('hospitals.*') ? 'bg-sky-50 dark:bg-sky-900/40 text-sky-700 dark:text-sky-300 font-bold' : 'text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-gray-800' }}">
                    {{ __('Hospitals') }}
                </a>
                <a href="{{ route('ambulances.index') }}" class="block px-3 py-2 rounded-lg text-sm {{ request()->routeIs('ambulances.*') ? 'bg-red-50 dark:bg-red-900/40 text-red-700 dark:text-red-300 font-bold' : 'text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-gray-800' }}">
                    {{ __('Ambulance') }}
                </a>
                <a href="{{ route('blog.index') }}" class="block px-3 py-2 rounded-lg text-sm {{ request()->routeIs('blog.*') ? 'bg-sky-50 dark:bg-sky-900/40 text-sky-700 dark:text-sky-300 font-bold' : 'text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-gray-800' }}">
                    {{ __('Blog') }}
                </a>
                @auth
                    @if(!auth()->user()->hasAnyRole(['admin', 'doctor', 'hospital', 'editor', 'moderator']))
                    <a href="{{ route('user.dashboard') }}" class="block px-3 py-2 rounded-lg text-sm text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-gray-800 font-medium">
                        👤 {{ __('My Dashboard') }}
                    </a>
                    @endif
                    <a href="{{ route('favorites.index') }}" class="block px-3 py-2 rounded-lg text-sm text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-gray-800">
                        ❤️ {{ __('Favorites') }}
                    </a>
                    @if(auth()->user()->hasRole('admin'))
                    <a href="{{ route('admin.dashboard') }}" class="block px-3 py-2 rounded-lg text-sm text-indigo-600 dark:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-gray-800">
                        🛡️ {{ __('Admin Panel') }}
                    </a>
                    @elseif(auth()->user()->hasRole('doctor'))
                    <a href="{{ route('doctor.dashboard') }}" class="block px-3 py-2 rounded-lg text-sm text-sky-600 dark:text-sky-400 hover:bg-sky-50 dark:hover:bg-gray-800">
                        👨‍⚕️ {{ __('Doctor Dashboard') }}
                    </a>
                    @elseif(auth()->user()->hasRole('hospital'))
                    <a href="{{ route('hospital.dashboard') }}" class="block px-3 py-2 rounded-lg text-sm text-emerald-600 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-gray-800">
                        🏥 {{ __('Hospital Dashboard') }}
                    </a>
                    @endif
                    <form method="POST" action="{{ route('logout') }}" class="px-3 pt-1">
                        @csrf
                        <button type="submit" class="w-full text-left py-2 text-sm text-red-500 font-medium">
                            🚪 {{ __('Logout') }}
                        </button>
                    </form>
                @else
                    <a href="{{ route('login') }}" class="block px-3 py-2 rounded-lg text-sm font-medium text-sky-600">{{ __('Login') }}</a>
                    <a href="{{ route('register') }}" class="block px-3 py-2 rounded-lg text-sm font-medium text-gray-600 dark:text-gray-300">{{ __('Register') }}</a>
                @endauth

            </div>
        </div>
    </nav>

    {{-- Flash messages --}}
    @if(session('success'))
        <div x-data="{ show: true }" x-show="show" x-init="setTimeout(() => show = false, 4000)"
             class="fixed top-20 right-4 z-50 max-w-sm bg-green-500 text-white px-5 py-3 rounded-xl shadow-xl flex items-center gap-3 text-sm font-medium animate-fade-in">
            <svg class="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
            <span>{{ session('success') }}</span>
            <button aria-label="Close alert" @click="show = false" class="ml-auto opacity-70 hover:opacity-100">✕</button>
        </div>
    @endif
    @if(session('error'))
        <div x-data="{ show: true }" x-show="show" x-init="setTimeout(() => show = false, 4000)"
             class="fixed top-20 right-4 z-50 max-w-sm bg-red-500 text-white px-5 py-3 rounded-xl shadow-xl flex items-center gap-3 text-sm font-medium">
            <svg class="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
            <span>{{ session('error') }}</span>
            <button aria-label="Close alert" @click="show = false" class="ml-auto opacity-70 hover:opacity-100">✕</button>
        </div>
    @endif

    {{-- ═══════════════════════════════════════
         MAIN CONTENT
    ═══════════════════════════════════════ --}}
    <main>
        @yield('content')
    </main>

    {{-- ═══════════════════════════════════════
         FOOTER
    ═══════════════════════════════════════ --}}
    <footer class="bg-[#0A2540] text-gray-200 mt-16 shadow-[0_-4px_10px_rgba(0,0,0,0.05)]">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <div class="grid grid-cols-1 md:grid-cols-5 gap-8">
                {{-- Brand --}}
                <div class="md:col-span-2">
                    <div class="flex items-center gap-2 mb-4">
                        @if(setting('site_logo'))
                            <img src="{{ asset('storage/' . setting('site_logo')) }}" alt="{{ setting('site_name', 'DoctorBD24') }}" class="h-9 w-auto bg-white p-1 rounded">
                        @else
                            <div class="w-9 h-9 rounded-xl bg-gradient-to-br from-sky-500 to-indigo-600 flex items-center justify-center">
                                <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
                                </svg>
                            </div>
                        @endif
                        <span class="text-xl font-extrabold text-white">{{ setting('site_name', 'DoctorBD24') }}</span>
                    </div>
                    <p class="text-sm text-gray-400 leading-relaxed max-w-xs">
                        {{ __("Bangladesh's largest healthcare directory. Find the right doctor, go to the best hospital.") }}
                    </p>
                </div>

                {{-- Quick links --}}
                <div>
                    <h4 class="font-semibold text-white mb-3">{{ __('Quick Links') }}</h4>
                    <ul class="space-y-2 text-sm">
                        <li><a href="{{ route('doctors.index') }}" class="hover:text-sky-400 transition-colors">{{ __('Doctors') }}</a></li>
                        <li><a href="{{ route('hospitals.index') }}" class="hover:text-sky-400 transition-colors">{{ __('Hospitals') }}</a></li>
                        <li><a href="{{ route('ambulances.index') }}" class="hover:text-sky-400 transition-colors">{{ __('Ambulance') }}</a></li>
                        <li><a href="{{ route('blog.index') }}" class="hover:text-sky-400 transition-colors">{{ __('Health Blog') }}</a></li>
                    </ul>
                </div>

                {{-- Information --}}
                <div>
                    <h4 class="font-semibold text-white mb-3">{{ __('Information') }}</h4>
                    <ul class="space-y-2 text-sm">
                        <li><a href="{{ route('page.show', ['slug' => 'about-us']) }}" class="hover:text-sky-400 transition-colors">{{ __('About Us') }}</a></li>
                        <li><a href="{{ route('contact') }}" class="hover:text-sky-400 transition-colors">{{ __('Contact Us') }}</a></li>
                        <li><a href="{{ route('page.show', ['slug' => 'privacy-policy']) }}" class="hover:text-sky-400 transition-colors">{{ __('Privacy Policy') }}</a></li>
                        <li><a href="{{ route('page.show', ['slug' => 'terms-and-conditions']) }}" class="hover:text-sky-400 transition-colors">{{ __('Terms & Conditions') }}</a></li>
                    </ul>
                </div>

                {{-- Join --}}
                <div>
                    <h4 class="font-semibold text-white mb-3">{{ __('For Professionals') }}</h4>
                    <ul class="space-y-2 text-sm">
                        <li><a href="{{ route('join.doctor') }}" class="hover:text-sky-400 transition-colors">{{ __('Join as Doctor') }}</a></li>
                        <li><a href="{{ route('join.hospital') }}" class="hover:text-sky-400 transition-colors">{{ __('List your Hospital') }}</a></li>
                        @guest
                        <li><a href="{{ route('register') }}" class="hover:text-sky-400 transition-colors">{{ __('Create Account') }}</a></li>
                        @endguest
                    </ul>
                </div>
            </div>

            <div class="border-t border-gray-800 mt-8 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-gray-500">
                <p>© {{ date('Y') }} {{ setting('site_name', 'DoctorBD24') }}. {{ __('All rights reserved.') }}</p>
                <p>{{ __('Made with ❤️ for Bangladesh') }}</p>
            </div>
        </div>
    </footer>

    @livewireScripts
    
    <script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('locationPicker', (initialDiv, initialDist, initialArea) => ({
            divisionId: initialDiv ? String(initialDiv) : '',
            districtId: initialDist ? String(initialDist) : '',
            areaId:     initialArea ? String(initialArea) : '',
            districts: [],
            areas: [],
            async init() {
                if (this.divisionId) {
                    await this.fetchDistricts(true);
                    if (this.districtId) await this.fetchAreas(true);
                }
            },
            async fetchDistricts(isInit = false) {
                this.districts = []; 
                if (!isInit) this.areas = [];
                const keep = this.districtId;
                this.districtId = ''; 
                if (!isInit) this.areaId = '';
                if (!this.divisionId) return;
                try {
                    let res = await fetch(`/api/districts?division_id=${this.divisionId}`);
                    this.districts = await res.json();
                } catch (err) {
                    console.error('fetchDistricts() ERROR:', err);
                }
                if (keep && this.districts.some(d => String(d.id) === keep)) this.districtId = keep;
            },
            async fetchAreas(isInit = false) {
                this.areas = [];
                const keep = this.areaId;
                this.areaId = '';
                if (!this.districtId) return;
                try {
                    let res = await fetch(`/api/areas?district_id=${this.districtId}`);
                    this.areas = await res.json();
                } catch (err) {
                    console.error('fetchAreas() ERROR:', err);
                }
                if (keep && this.areas.some(a => String(a.id) === keep)) this.areaId = keep;
            }
        }));
    });
    </script>

    @stack('scripts')

    <!-- Global Toast Component -->
    <div x-data="{
        show: false,
        message: '',
        type: 'info',
        timeout: null,
        init() {
            window.addEventListener('toast', e => {
                this.message = e.detail.message;
                this.type = e.detail.type || 'info';
                this.show = true;
                clearTimeout(this.timeout);
                this.timeout = setTimeout(() => { this.show = false; }, 3000);
            });
        }
    }" 
    x-show="show" 
    x-transition:enter="transition ease-out duration-300" 
    x-transition:enter-start="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2" 
    x-transition:enter-end="translate-y-0 opacity-100 sm:translate-x-0" 
    x-transition:leave="transition ease-in duration-100" 
    x-transition:leave-start="opacity-100" 
    x-transition:leave-end="opacity-0" 
    class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-end sm:p-6 z-50 justify-end" style="display: none;">
        <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-gray-800 shadow-lg ring-1 ring-black ring-opacity-5">
            <div class="p-4">
                <div class="flex items-start">
                    <div class="flex-shrink-0">
                        <template x-if="type === 'warning'">
                            <svg class="h-6 w-6 text-yellow-400" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                        </template>
                        <template x-if="type === 'info'">
                            <svg class="h-6 w-6 text-sky-400" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
                            </svg>
                        </template>
                    </div>
                    <div class="ml-3 w-0 flex-1 pt-0.5">
                        <p class="text-sm font-medium text-white" x-text="message"></p>
                    </div>
                    <div class="ml-4 flex flex-shrink-0">
                        <button type="button" @click="show = false" class="inline-flex rounded-md bg-gray-800 text-gray-400 hover:text-gray-300 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2">
                            <span class="sr-only">Close</span>
                            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
